name: Docker Image CI


on:
  #  pull_request:
  #    types:
  #      - closed
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: test_actions_registry

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Log to the GitHub registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME
      
    - name: Push image to the GitHub registry
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        
        VERSION=$GITHUB_SHA
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo IMAGE_NAME=$IMAGE_NAME

        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        docker tag $IMAGE:$VERSION $IMAGE:latest
        docker push $IMAGE:latest
